;============================================================================================================
; CHESSBRAINVB.INI 
; =================
; chess engine ChessBrainVB V3 for winboard and UCI interfaces like Arena GUI. by Roger Zuehlsdorf (2018)
; based on LarsenVB by Luca Dormio (http://xoomer.virgilio.it/ludormio/download.htm) and Faile 
; by Adrien M. Regimbald
; and ideas from Stockfish, Protector and other engines.
; Author: Roger Zuehlsdorf (2026) / Email: rogzuehlsdorf@yahoo.de
; Github sources:  https://github.com/RZulu54
;============================================================================================================

;============================================================================================================
;--- Settings for chess engine
;============================================================================================================
[Engine]

; if not winboard path set: for ARENA GUI use XBOARD Mode
XBOARD_MODE=1
; in winbord mode show PV line without extra character like x !
WB_PV_IN_UCI=0

; Opening book, empty entry for no book or rename file ( use ARENA main book for better results )
OPENING_BOOK=
;OPENING_BOOK=
;OPENING_BOOK=CB_BOOK.TXT
; if no book above is found then use a small dummy book for fun (1=aktive, 0 = off, empty: OfficeMode=1, UCI/WB=0)
USE_INTERNAL_BOOK=
;USE_INTERNAL_BOOK=1
;USE_INTERNAL_BOOK=0

; set number of threads (max 8); 0 or 1: normal single thread, 2-8: multiple processes of EXE running
; Winboard "cores" command overrides this setting if cores value > THREADS (UCI setting overrides too )
THREADS=1
; Threads send from GUI ignored if set
THREADS_IGNORE_GUI=0
;THREADS_IGNORE_GUI=1

; Hash size in MB. (31 bytes per entry) (UCI/WB settings overrides if higher)
; max 1400 MB 
HASHSIZE=64
; Hash used value will be overwritten by main task to communicate with helper threads
HASH_USED=64
; Hash size send from GUI ignored if set
HASHSIZE_IGNORE_GUI=0
;HASHSIZE_IGNORE_GUI=1

; Verify Hash reads to handle hash collisions, slows down engine 5%, but avoids some bad moves
HASH_VERIFY=1

; Overhead for move communication to GUI and start/stop thinking in milliseconds (more threads may need more? 1000ms)
; recommended for ARENA: 800ms, for ChessGUI 1000ms, for SMP 1500ms
MOVEOVERHEAD=1000

; Contempt value: draw score in centipawns(100= 1Pawn) from engine view. Against better engine set positive value
CONTEMPT=1

;============================================================================================================
;--- Evaluation of position (factor in percent: 100 = unchanged score, 0 = zero score,  200 = double score) 
;============================================================================================================
; Position: piece position evaluation values(i.e. piece square tables)
POSITION_FACTOR=100

; Mobility: mobility of pieces
MOBILITY_FACTOR=100

; Pawn structure: pawn value depending on supported, isolated, backwards,...
PAWNSTRUCT_FACTOR=100

; Passed pawns: passed pawns value depending on rank, safe advance to promote square,...
PASSEDPAWNS_FACTOR=120
;PASSEDPAWNS_FACTOR=100

; Threats: bonus for threats at opponent pieces depending on piece types
THREATS_FACTOR=100
;THREATS_FACTOR=100

; Opponent king attack: bonus for safe king shelter, penalty for attack options
OPPKINGATT_FACTOR=100
;OPPKINGATT_FACTOR=100

; Computer king defense: bonus for safe king shelter, penalty for attack options
COMPKINGDEF_FACTOR=100
;COMPKINGDEF_FACTOR=100

;============================================================================================================
;--- Piece values (MG: Midgame, EG: Endgame for scaling using game phases) based on Stockfish6 ---
;--- This values are default in engine if entries are missing here
;============================================================================================================
PAWN_VAL_MG=142
PAWN_VAL_EG=207

KNIGHT_VAL_MG=784
KNIGHT_VAL_EG=868

BISHOP_VAL_MG=828
BISHOP_VAL_EG=916

ROOK_VAL_MG=1286
ROOK_VAL_EG=1378

QUEEN_VAL_MG=2528
QUEEN_VAL_EG=2698

; for game phase calculation
MIDGAME_LIMIT=15258
ENDGAME_LIMIT=3915


;============================================================================================================
;--- Debug settings
;============================================================================================================
;enable PV log = 1 ; disable PV log =0 , same as command parameter "-log".
LogPV=0

;Trace file settings: 0 / 1
EVALTRACE=0
TIMETRACE=0
HASHTRACE=0
HASH_COLL_TRACE=0
COMMANDTRACE=0
TBBASE_TRACE=0
THREADTRACE=0

;============================================================================================================
